version: '3.8'

services:
  app:
    build: .
    container_name: nest-app
    restart: always
    env_file:
      - .env
    ports:
      - '3001:3001'
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: farmdex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
